name: Playwright Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: npm run install:ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build client
        run: cd packages/client && npm run build

      - name: Start services
        run: |
          cd packages/server && go run main.go &
          cd packages/client && npx next start &
          npx wait-on http://localhost:3000
        env:
          NEXT_PUBLIC_CI_TEST: 'true'

      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
